import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export const useStore = create(persist((set) => ({
    carrier: 'composite',
    simulationHoursAhead: 0,
    weatherScenario: 'live',
    heatTiles: [],
    originText: "Whitefield",
    destinationText: "MG Road",
    setOriginText: (originText) => set({ originText }),
    setDestinationText: (destinationText) => set({ destinationText }),
    origin: null,
    destination: null,
    routes: [],
    selectedRouteIdx: 0,
    alpha: 0.65,
    persona: 'default',
    personaPreset: 'default',
    setCarrier: (carrier) => set({ carrier }),
    setSimulationHoursAhead: (simulationHoursAhead) => set({ simulationHoursAhead }),
    setWeatherScenario: (weatherScenario) => set({ weatherScenario }),
    setAlpha: (alpha) => set({ alpha }),
    setPersonaPreset: (personaPreset) => set({
        personaPreset,
        persona: personaPreset === 'custom' ? 'default' : personaPreset,
    }),
    isNavigating: false,
    currentNavSignal: null,
    setCurrentNavSignal: (currentNavSignal) => set({ currentNavSignal }),
    setIsNavigating: (val) => set({ isNavigating: val, navProgress: 0, currentNavSignal: null }),
    navProgress: 0,
    setNavProgress: (val) => set({ navProgress: val }),
    originCoords: [77.7499, 12.9698],
    destinationCoords: [77.6013, 12.9716],
    setOriginCoords: (coords) => set({ originCoords: coords }),
    setDestinationCoords: (coords) => set({ destinationCoords: coords }),
    dynamicRouteData: null,
    setDynamicRouteData: (data) => set({ dynamicRouteData: data }),
    weatherConditions: null,
    setWeatherConditions: (weatherConditions) => set({ weatherConditions }),
    
    // BACKEND INTEGRATION STATES
    routeCacheKey: null,
    setRouteCacheKey: (key) => set({ routeCacheKey: key }),
    mapSelectionMode: null,
    setMapSelectionMode: (mapSelectionMode) => set({ mapSelectionMode }),
    isDarkMode: true,
    toggleDarkMode: () => set((state) => ({ isDarkMode: !state.isDarkMode })),
    mapStyle: 'normal',
    setMapStyle: (mapStyle) => set({ mapStyle }),
    cameraMode: 'driver',
    setCameraMode: (cameraMode) => set({ cameraMode }),
}), {
    name: 'neuralpath-ui',
    partialize: (state) => ({
        carrier: state.carrier,
        weatherScenario: state.weatherScenario,
        isDarkMode: state.isDarkMode,
        mapStyle: state.mapStyle,
        cameraMode: state.cameraMode,
    }),
}))
